version: "3.8"

services:

  # База данных
  keycloak-postgres:
    image: postgres:12.9-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    networks:
      - efi2-network


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    platform: linux/arm64
    command:
      - start --db postgres --http-port=8484 --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true 
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8484:8484"
    depends_on:
      - keycloak-postgres
    networks:
      - efi2-network

networks:
  efi2-network:
